### ISSUE TITLE
Feature request: Specify frame or percentage

### ISSUE THREAD

**Issue by phillipseamore** [cshum/imagorvideo#14]
Thanks for these great projects, I've been using imagor for a while and imagorvideo will help me get rid of a bunch of shell scripts I'm using to do thumbnails.

I'd like to request the option of getting a specific frame or a frame close to a certain percentage of the duration.

Requesting frame number 74:
`http://localhost:8000/unsafe/fit-in/300x200/filters:frame(74)/https://raw.githubusercontent.com/ietf-wg-cellar/matroska-test-files/master/test_files/test4.mkv`

Requesting a frame from around the middle of a video (floating number between 0.0-1.0 would be percentage of duration, integer a frame):
`http://localhost:8000/unsafe/fit-in/300x200/filters:frame(0.5)/https://raw.githubusercontent.com/ietf-wg-cellar/matroska-test-files/master/test_files/test4.mkv`

`0.0` would then be first frame and `1.0` would be last.

I work with a lot of files that are single keyframe MP4's. Imagorvideo doesn't seem to handle them, giving error: "imagor: 406 ffmpeg: invalid data found when processing input". Attached is one example of such a file (the image is mostly dark with some streetlights [past midnight over here]). I'm hoping that being able to request the first frame will allow me to use those as input.

https://user-images.githubusercontent.com/3772845/194165101-1ab4772d-41fe-4379-b778-35c0f5e26392.mp4

**Comment by cshum** [comment]
@phillipseamore would you test if this docker build fixes the single keyframe MP4's issue?

```
docker run --rm -p 8000:8000 ghcr.io/cshum/imagorvideo@sha256:dd5428fe6b923a380a606b98a37f297f09b1f51da3818246c3c53274a5d0e79c -imagor-unsafe
```
https://github.com/cshum/imagorvideo/pkgs/container/imagorvideo/44725393?tag=master

**Comment by cshum** [comment]
The fix is now available at v0.1.4. 

The requesting frame number `frame(74)` sounds reasonable enough, I am keen to implement it in coming versions. 

Requesting frame percentage would be way more tricky though. The current implementation is based on selecting the first `n` frames then compute, without looping through the entire video. Seeking to a specific location would be an entirely different paradigm, presumably way more resource intensive. 

That being said, I am very new to the ffmpeg libraries. For anyone experienced with ffmpeg I am very keen to hear your opinion. As usual, any PRs are welcomed!

**Comment by cshum** [comment]
v0.2.0 added FPS to meta if frame processing is activated, also changed duration to milliseconds instead:
https://github.com/cshum/imagorvideo#metadata

Added `frame(n)` and `max_frames(n)` filters thought they are currently based on the existing "select first n frames" mechanism.

**Comment by cshum** [comment]
The master branch build adding seek support based on time or percentage:
https://github.com/cshum/imagorvideo/pkgs/container/imagorvideo/46797504?tag=master
```
docker run --rm -p 8000:8000 ghcr.io/cshum/imagorvideo@sha256:21f0bce4626927bf3c867d1e4880cc7181c42b1e0089cac5a918b56291333b9c -imagor-unsafe
```
Try `frame(2m1s)` and `frame(0.7)` filter:
```
http://localhost:8000/unsafe/filters:frame(2m1s)/http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4
http://localhost:8000/unsafe/filters:frame(0.7)/http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4
```
https://github.com/cshum/imagorvideo/blob/master/ffmpeg/ffmpeg.go#L236
The current implementation is based on `AVSEEK_FLAG_BACKWARD`, which indicates closest keyframe having a smaller timestamp. All other seek options seem much more prone to errors
